ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_acmi2.txt pg_acmi2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_aeca.txt pg_aeca.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_albib.txt pg_albib.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_alhy.txt pg_alhy.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_alin2.txt pg_alin2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_alinr.txt pg_alinr.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_alru2.txt pg_alru2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_alun.txt pg_alun.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ambr2.txt pg_ambr2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_anca10.txt pg_anca10.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_apam.txt pg_apam.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_apca.txt pg_apca.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_arcac.txt pg_arcac.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ardo3.txt pg_ardo3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ardr4.txt pg_ardr4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_areg.txt pg_areg.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_arfr4.txt pg_arfr4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_argi.txt pg_argi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_arlu.txt pg_arlu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_arme.txt pg_arme.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_arvi4.txt pg_arvi4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_asca.txt pg_asca.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_asco.txt pg_asco.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_asfa.txt pg_asfa.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_assy.txt pg_assy.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_astr.txt pg_astr.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_astu.txt pg_astu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_baau.txt pg_baau.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_brco3.txt pg_brco3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_caam2.txt pg_caam2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_caba4.txt pg_caba4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_caci2.txt pg_caci2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cagi7.txt pg_cagi7.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cail2.txt pg_cail2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_calu9.txt pg_calu9.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_caob3.txt pg_caob3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_caqub2.txt pg_caqub2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_caquq.txt pg_caquq.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_casu3.txt pg_casu3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cave3.txt pg_cave3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ceam.txt pg_ceam.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ceca4.txt pg_ceca4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cecu.txt pg_cecu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cehe.txt pg_cehe.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cela.txt pg_cela.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ceor9.txt pg_ceor9.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_chpo3.txt pg_chpo3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_coes.txt pg_coes.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cose16.txt pg_cose16.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_coseo.txt pg_coseo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_coses.txt pg_coses.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_cyer.txt pg_cyer.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_dica14.txt pg_dica14.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_dicac5.txt pg_dicac5.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_dicap.txt pg_dicap.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ecan2.txt pg_ecan2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ecpu.txt pg_ecpu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_epne.txt pg_epne.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_epvi.txt pg_epvi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_eraq.txt pg_eraq.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_erca6.txt pg_erca6.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_erph.txt pg_erph.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_fraf2.txt pg_fraf2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_fram2.txt pg_fram2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frca5.txt pg_frca5.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frca6.txt pg_frca6.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frch.txt pg_frch.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frchc.txt pg_frchc.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frchl.txt pg_frchl.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frchp.txt pg_frchp.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frchs2.txt pg_frchs2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frni.txt pg_frni.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frve.txt pg_frve.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_frvi.txt pg_frvi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_gusa2.txt pg_gusa2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_gydi.txt pg_gydi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_hean3.txt pg_hean3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_hear5.txt pg_hear5.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_hefa.txt pg_hefa.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_hihia.txt pg_hihia.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_hiod.txt pg_hiod.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_hyhyh.txt pg_hyhyh.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ilvo.txt pg_ilvo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_irdo.txt pg_irdo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_irfe.txt pg_irfe.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_irma.txt pg_irma.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_irmi.txt pg_irmi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_irpu.txt pg_irpu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_irvi.txt pg_irvi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_juba.txt pg_juba.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_juef.txt pg_juef.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_jule.txt pg_jule.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_juni.txt pg_juni.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_jupi.txt pg_jupi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_jusc2.txt pg_jusc2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_jute2.txt pg_jute2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_juvi.txt pg_juvi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_leca8.txt pg_leca8.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_legr.txt pg_legr.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_lere7.txt pg_lere7.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_lide3.txt pg_lide3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_lipa.txt pg_lipa.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_list2.txt pg_list2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_loca2.txt pg_loca2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_loin.txt pg_loin.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_losi.txt pg_losi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_luno.txt pg_luno.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_lupe3.txt pg_lupe3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_mael.txt pg_mael.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_maes.txt pg_maes.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_main3.txt pg_main3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_masa.txt pg_masa.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_medi.txt pg_medi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_moca6.txt pg_moca6.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_mofi.txt pg_mofi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_mopu.txt pg_mopu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_moru2.txt pg_moru2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_muri2.txt pg_muri2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_nomi.txt pg_nomi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_oebi.txt pg_oebi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_opac.txt pg_opac.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pain3.txt pg_pain3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pain6.txt pg_pain6.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_paqu.txt pg_paqu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pegr7.txt pg_pegr7.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pied.txt pg_pied.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pimo.txt pg_pimo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pipa2.txt pg_pipa2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pira2.txt pg_pira2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pire.txt pg_pire.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pisa2.txt pg_pisa2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pisi.txt pg_pisi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_plci2.txt pg_plci2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ploc.txt pg_ploc.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_poan3.txt pg_poan3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pobat.txt pg_pobat.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pofr2.txt pg_pofr2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_poin3.txt pg_poin3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_potr5.txt pg_potr5.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pram.txt pg_pram.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prem.txt pg_prem.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prgl2.txt pg_prgl2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prglt.txt pg_prglt.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_pril.txt pg_pril.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prpa2.txt pg_prpa2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prpu.txt pg_prpu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prve.txt pg_prve.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_prvi.txt pg_prvi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_psme.txt pg_psme.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_quag.txt pg_quag.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_qubi.txt pg_qubi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_qudo.txt pg_qudo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_quke.txt pg_quke.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_quru.txt pg_quru.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_qush.txt pg_qush.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_quwi2.txt pg_quwi2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_raco3.txt pg_raco3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rapi.txt pg_rapi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhar4.txt pg_rhar4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhara.txt pg_rhara.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhara2.txt pg_rhara2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhars.txt pg_rhars.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhgl.txt pg_rhgl.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtr.txt pg_rhtr.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtra.txt pg_rhtra.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtrp.txt pg_rhtrp.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtrq.txt pg_rhtrq.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtrr.txt pg_rhtrr.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtrs.txt pg_rhtrs.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rhtrt.txt pg_rhtrt.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_riau.txt pg_riau.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_riaua.txt pg_riaua.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_riaug.txt pg_riaug.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_riauv.txt pg_riauv.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rovi2.txt pg_rovi2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rovil.txt pg_rovil.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_roviv2.txt pg_roviv2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rowog.txt pg_rowog.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rowog2.txt pg_rowog2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rowou.txt pg_rowou.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rowow.txt pg_rowow.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ruid.txt pg_ruid.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_rusp.txt pg_rusp.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_saal5.txt pg_saal5.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_saam2.txt pg_saam2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_saap2.txt pg_saap2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sabe2.txt pg_sabe2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_saco6.txt pg_saco6.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sacu.txt pg_sacu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_saex.txt pg_saex.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sahu2.txt pg_sahu2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sala2.txt pg_sala2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_salu.txt pg_salu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_salul.txt pg_salul.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sami8.txt pg_sami8.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sanic4.txt pg_sanic4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sanic5.txt pg_sanic5.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sapa.txt pg_sapa.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sasi2.txt pg_sasi2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_scaco2.txt pg_scaco2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_scam6.txt pg_scam6.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_scca11.txt pg_scca11.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sccy.txt pg_sccy.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_scta2.txt pg_scta2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sere2.txt pg_sere2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_shca.txt pg_shca.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sipe2.txt pg_sipe2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sipec2.txt pg_sipec2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sipep.txt pg_sipep.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_spai.txt pg_spai.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_spam.txt pg_spam.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_span.txt pg_span.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_span2.txt pg_span2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sper.txt pg_sper.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_spers2.txt pg_spers2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_speu.txt pg_speu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_spfl.txt pg_spfl.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_spgl.txt pg_spgl.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sphy.txt pg_sphy.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_spna.txt pg_spna.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sthe4.txt pg_sthe4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_syal.txt pg_syal.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_sylal4.txt pg_sylal4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_syno2.txt pg_syno2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_synon.txt pg_synon.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_syvu.txt pg_syvu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_thoc2.txt pg_thoc2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_thpl.txt pg_thpl.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tiam.txt pg_tiam.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tiama.txt pg_tiama.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tiamc.txt pg_tiamc.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tiamh.txt pg_tiamh.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tius.txt pg_tius.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_trhy3.txt pg_trhy3.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_trix.txt pg_trix.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_trla16.txt pg_trla16.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_trla4.txt pg_trla4.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_trvi.txt pg_trvi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_trwo.txt pg_trwo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tsca.txt pg_tsca.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tshe.txt pg_tshe.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tyan.txt pg_tyan.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tydo.txt pg_tydo.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_tyla.txt pg_tyla.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ulpu.txt pg_ulpu.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_ulru.txt pg_ulru.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_umca.txt pg_umca.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_vade.txt pg_vade.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_vame.txt pg_vame.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_vaov2.txt pg_vaov2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_vaox.txt pg_vaox.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_vapa.txt pg_vapa.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_vasc.txt pg_vasc.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_viopa2.txt pg_viopa2.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_wafi.txt pg_wafi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_yufi.txt pg_yufi.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_yuwh.txt pg_yuwh.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_zaam.txt pg_zaam.txt
ren D:\pythonProjects\DBMS-crawler\main\data_1\cs_zapu.txt pg_zapu.txt